package unittest.fail;

public class CatchingError1 {
	{
		try {
			new String();
		} catch (Error e) {
			
		}
	}
}
